version: '3'

services: 

  app:
    container_name: app
    restart: "always"
    build:
      context: ./app
    networks: 
      - node-network
    volumes: 
      - ./app:/usr/src/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    tty: true
    depends_on: 
       - db

  db:
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    build:
      context: ./mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  web:
    container_name: web
    restart: "always"
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - node-network
    ports:
      - "8080:80"
    links: 
      - app
    

networks: 
  node-network:
    driver: bridge      
